In [1]:
import os
import sys

## CHANGE THIS
dir2 = os.path.abspath("/volume/Orion/orion")
dir1 = os.path.dirname(dir2)
if not dir1 in sys.path:
    sys.path.append(dir1)
import importlib

importlib.util.find_spec("orion")
# import torch
import csv

import numpy as np
import pandas as pd
from IPython.core.display import HTML, display

display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option("display.max_rows", 50)
pd.set_option("display.max_columns", 250)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 300)
pd.options.mode.chained_assignment = None  # default='warn'

def df_stats(df):
    from tabulate import tabulate

    print("\n***** Shape: ", df.shape, " *****\n")

    df_stat_val = pd.DataFrame({
        "Name": df.columns,
        "Null": df.isnull().sum(),
        "Unique": df.nunique(),
        "Dtypes": df.dtypes
    })

    print(tabulate(df_stat_val, headers="keys", tablefmt="psql"))
    return df.head()

/tmp/ipykernel_1151253/499724434.py:17: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display

In [10]:
df = pd.read_parquet('../data/deepcoro_split_dataset.parquet')
# Remove all rows where main_structure_class == 2 and save the result to main_structure_class
main_structure_class = df[df['main_structure_class'] != 2].copy()

In [ ]:
display(df_stats(main_structure_class))

***** Shape:  (843499, 789)  *****

+------------------------------------------+------------------------------------------+--------+----------+----------------+
|                                          | Name                                     |   Null |   Unique | Dtypes         |
|------------------------------------------+------------------------------------------+--------+----------+----------------|
| CathReport_MRN                           | CathReport_MRN                           |      0 |    34886 | int64          |
| EXAMEN_ID                                | EXAMEN_ID                                |      0 |    45558 | int64          |
| Num Accession                            | Num Accession                            |      0 |    45558 | object         |
| DICOMPath                                | DICOMPath                                |      0 |   843499 | object         |
| ModalitiesInStudy                        | ModalitiesInStudy                        |      0 |        2 | object         |
| Patient_ID                               | Patient_ID                               |      0 |    34886 | int64          |
| QueryRetrieveLevel                       | QueryRetrieveLevel                       |      0 |        2 | object         |
| StudyDate                                | StudyDate                                |      0 |    44806 | datetime64[ns] |
| StudyInstanceUID                         | StudyInstanceUID                         |      0 |    45560 | object         |
| StudyTime                                | StudyTime                                | 114587 |    25029 | float64        |
| year                                     | year                                     |      0 |        8 | float64        |
| patient_id_anon                          | patient_id_anon                          |      0 |    32531 | object         |
| dicom_id_x                               | dicom_id_x                               | 741302 |   102197 | object         |
| study_time                               | study_time                               |      0 |    22605 | int64          |
| series_time                              | series_time                              |      0 |    63627 | int64          |
| IDPATIENT                                | IDPATIENT                                |     42 |    34886 | float64        |
| DATEEXAMEN                               | DATEEXAMEN                               |     42 |     2804 | datetime64[ns] |
| TYPEEXAMEN                               | TYPEEXAMEN                               |      0 |       10 | object         |
| CATEGORIE                                | CATEGORIE                                |     42 |        1 | float64        |
| SOUSCATEGORIE                            | SOUSCATEGORIE                            |     42 |        1 | float64        |
| TITREEXAMEN                              | TITREEXAMEN                              |      0 |      960 | object         |
| HEUREDEBUT                               | HEUREDEBUT                               |   4822 |     1362 | object         |
| HEUREFIN                                 | HEUREFIN                                 |  26970 |     3356 | object         |
| SALLE                                    | SALLE                                    |      0 |       10 | object         |
| NSEJOUR                                  | NSEJOUR                                  |      0 |    45556 | object         |
| FACTIVE                                  | FACTIVE                                  |     42 |        1 | float64        |
| TYPEPROVENANCE                           | TYPEPROVENANCE                           |      0 |        6 | object         |
| POIDS                                    | POIDS                                    |  25168 |     1059 | float64        |
| TAILLE                                   | TAILLE                                   |  37012 |       89 | float64        |
| HOSPITAL                                 | HOSPITAL                                 |      0 |        4 | object         |
| Urgency                                  | Urgency                                  |      0 |        5 | object         |
| CREATININE                               | CREATININE                               | 125609 |      638 | float64        |
| CK                                       | CK                                       | 843361 |        8 | float64        |
| HEMOGLOBINE                              | HEMOGLOBINE                              | 157430 |      300 | float64        |
| PLAQUETTES                               | PLAQUETTES                               | 165631 |      593 | float64        |
| TNI                                      | TNI                                      | 724665 |      592 | float64        |
| TROPHS                                   | TROPHS                                   | 688014 |     1358 | float64        |
| ANGINA                                   | ANGINA                                   |      0 |       12 | object         |
| ISCHEMIA                                 | ISCHEMIA                                 |      0 |       14 | object         |
| LOCALISATIONISCHEMIE                     | LOCALISATIONISCHEMIE                     |      0 |       12 | object         |
| LV                                       | LV                                       |      0 |        6 | object         |
| DIABETES_HISTORY                         | DIABETES_HISTORY                         |      0 |        8 | object         |
| HYPERTENSION                             | HYPERTENSION                             |      0 |        8 | object         |
| SMOKING                                  | SMOKING                                  |      0 |        6 | object         |
| CAD_HISTORY                              | CAD_HISTORY                              |      0 |        5 | object         |
| OTHERSURGERY                             | OTHERSURGERY                             |      0 |        9 | object         |
| STROKE                                   | STROKE                                   |      0 |        8 | object         |
| VASCULAR                                 | VASCULAR                                 |      0 |        6 | object         |
| FIBRILLATION                             | FIBRILLATION                             |      0 |        9 | object         |
| TV                                       | TV                                       |      0 |        5 | object         |
| PM                                       | PM                                       |      0 |        5 | object         |
| CABG                                     | CABG                                     |      0 |       10 | object         |
| LV.1                                     | LV.1                                     |      0 |        7 | object         |
| LVEF                                     | LVEF                                     | 780511 |       67 | float64        |
| RENAL                                    | RENAL                                    |      0 |        8 | object         |
| VASCULARACCESS                           | VASCULARACCESS                           |      0 |       14 | object         |
| VASCULARACCESS2                          | VASCULARACCESS2                          |      0 |       13 | object         |
| FERMETUREART                             | FERMETUREART                             |      0 |       16 | object         |
| FERMETUREART2                            | FERMETUREART2                            |      0 |       16 | object         |
| VEINACCESS                               | VEINACCESS                               |      0 |       13 | object         |
| VEINACCESS2                              | VEINACCESS2                              |      0 |       12 | object         |
| FERMETUREVEIN                            | FERMETUREVEIN                            |      0 |        5 | object         |
| FERMETUREVEIN2                           | FERMETUREVEIN2                           |      0 |        5 | object         |
| METHERGIN                                | METHERGIN                                |      0 |        5 | object         |
| LAO                                      | LAO                                      |      0 |        3 | object         |
| RAO                                      | RAO                                      |      0 |        4 | object         |
| STENTS                                   | STENTS                                   |  64633 |       11 | float64        |
| BMS                                      | BMS                                      | 367729 |        6 | float64        |
| BALLONS                                  | BALLONS                                  |  64633 |        6 | float64        |
| TRONC0                                   | TRONC0                                   |  64633 |        4 | float64        |
| TRONC50                                  | TRONC50                                  |  64633 |        4 | float64        |
| IVA50                                    | IVA50                                    |  64633 |        8 | float64        |
| CX50                                     | CX50                                     |  64633 |        7 | float64        |
| CD50                                     | CD50                                     |  64643 |        9 | float64        |
| PONTAGES                                 | PONTAGES                                 |  64643 |        7 | float64        |
| TC50                                     | TC50                                     |  64643 |        3 | float64        |
| LESIONRESTENOSE                          | LESIONRESTENOSE                          |  64643 |       14 | float64        |
| STENTSACTIFRESTENOSE                     | STENTSACTIFRESTENOSE                     |  64643 |        5 | float64        |
| STENTSRESTENOSE                          | STENTSRESTENOSE                          |  64643 |        5 | float64        |
| PONTAGESMAMMAIRES50                      | PONTAGESMAMMAIRES50                      |  64643 |        3 | float64        |
| PONTAGESSAPHENES50                       | PONTAGESSAPHENES50                       |  64643 |        5 | float64        |
| DILATATIONS                              | DILATATIONS                              |  64643 |       11 | float64        |
| DILATATIONSPONTAGESSUCCES                | DILATATIONSPONTAGESSUCCES                |  64643 |        6 | float64        |
| TCDILATATIONS                            | TCDILATATIONS                            |  64643 |        3 | float64        |
| PONTAGESSAPHENES                         | PONTAGESSAPHENES                         |  64643 |        6 | float64        |
| LESIONSSTENTSACTIF                       | LESIONSSTENTSACTIF                       |  64643 |       11 | float64        |
| DILATATIONSPONTAGESECHEC                 | DILATATIONSPONTAGESECHEC                 |  64643 |        3 | float64        |
| DILATATIONSSUCCES                        | DILATATIONSSUCCES                        |  64643 |       10 | float64        |
| DILATATIONSECHEC                         | DILATATIONSECHEC                         |  64643 |        4 | float64        |
| LESIONSSTENTS                            | LESIONSSTENTS                            |  64643 |       11 | float64        |
| STENTSACTIFS                             | STENTSACTIFS                             |  64643 |       11 | float64        |
| PONTAGESMAMMAIRES                        | PONTAGESMAMMAIRES                        |  64643 |        4 | float64        |
| PONTAGES50                               | PONTAGES50                               |  64643 |        5 | float64        |
| BVS                                      | BVS                                      |  64643 |        5 | float64        |
| CDBMS                                    | CDBMS                                    | 660534 |        4 | float64        |
| CDBVS                                    | CDBVS                                    |  64643 |        3 | float64        |
| CDDEB                                    | CDDEB                                    |  64643 |        5 | float64        |
| CDDILATATIONS                            | CDDILATATIONS                            |  64643 |        8 | float64        |
| CDSTENTS                                 | CDSTENTS                                 |  64643 |        6 | float64        |
| CDSTENTSACTIF                            | CDSTENTSACTIF                            |  64643 |        6 | float64        |
| CIRCRESTENOSE                            | CIRCRESTENOSE                            |  64643 |        8 | float64        |
| CXBMS                                    | CXBMS                                    | 694966 |        3 | float64        |
| CXBVS                                    | CXBVS                                    |  64643 |        2 | float64        |
| CXDEB                                    | CXDEB                                    |  64643 |        4 | float64        |
| CXDILATATIONS                            | CXDILATATIONS                            |  64643 |        7 | float64        |
| CXSTENTS                                 | CXSTENTS                                 |  64643 |        5 | float64        |
| CXSTENTSACTIF                            | CXSTENTSACTIF                            |  64643 |        5 | float64        |
| DEB                                      | DEB                                      |  64643 |        6 | float64        |
| DILATATIONSPONTAGES                      | DILATATIONSPONTAGES                      |  64643 |        6 | float64        |
| DSTENTMAX                                | DSTENTMAX                                | 375974 |        9 | float64        |
| DSTENTMIN                                | DSTENTMIN                                | 375974 |        9 | float64        |
| DSTENTMOY                                | DSTENTMOY                                | 375974 |       14 | float64        |
| GRAFTRESTENOSE                           | GRAFTRESTENOSE                           |  64643 |        6 | float64        |
| GUIDEPRESSION                            | GUIDEPRESSION                            |  64643 |        2 | float64        |
| IVABMS                                   | IVABMS                                   | 601441 |        3 | float64        |
| IVABVS                                   | IVABVS                                   |  64643 |        3 | float64        |
| IVADEB                                   | IVADEB                                   |  64643 |        4 | float64        |
| IVADILATATIONS                           | IVADILATATIONS                           |  64643 |        7 | float64        |
| IVASTENTS                                | IVASTENTS                                |  64643 |        6 | float64        |
| IVASTENTSACTIF                           | IVASTENTSACTIF                           |  64643 |        6 | float64        |
| IVUS                                     | IVUS                                     |  64643 |        2 | float64        |
| LADRESTENOSE                             | LADRESTENOSE                             |  64643 |        8 | float64        |
| LESIONS50                                | LESIONS50                                |  64643 |       18 | float64        |
| LESIONSDILATATIONS                       | LESIONSDILATATIONS                       |  64643 |        5 | float64        |
| LMRESTENOSE                              | LMRESTENOSE                              |  64643 |        4 | float64        |
| LSTENT                                   | LSTENT                                   | 375974 |      189 | float64        |
| LSTENTMAX                                | LSTENTMAX                                | 375974 |       26 | float64        |
| LSTENTMIN                                | LSTENTMIN                                | 375974 |       25 | float64        |
| PONTAGESBMS                              | PONTAGESBMS                              | 815331 |        2 | float64        |
| PONTAGESBVS                              | PONTAGESBVS                              |  64643 |        1 | float64        |
| PONTAGESDEB                              | PONTAGESDEB                              |  64643 |        4 | float64        |
| PONTAGESDILATATIONS                      | PONTAGESDILATATIONS                      |  64643 |        6 | float64        |
| PONTAGESPERMEABLES                       | PONTAGESPERMEABLES                       |  64643 |        7 | float64        |
| PONTAGESSTENTS                           | PONTAGESSTENTS                           |  64643 |        6 | float64        |
| PONTAGESSTENTSACTIFS                     | PONTAGESSTENTSACTIFS                     |  64643 |        6 | float64        |
| RCARESTENOSE                             | RCARESTENOSE                             |  64643 |      165 | float64        |
| SYNTAX                                   | SYNTAX                                   |  64764 |       84 | float64        |
| TCBMS                                    | TCBMS                                    | 787711 |        2 | float64        |
| TCBVS                                    | TCBVS                                    |  64643 |        1 | float64        |
| TCDEB                                    | TCDEB                                    |  64643 |        3 | float64        |
| TCSTENTS                                 | TCSTENTS                                 |  64643 |        3 | float64        |
| TCSTENTSACTIF                            | TCSTENTSACTIF                            |  64643 |        3 | float64        |
| TRONCRESTENOSE                           | TRONCRESTENOSE                           |  64643 |        4 | float64        |
| Indications                              | Indications                              |      0 |     2789 | object         |
| Recommendation                           | Recommendation                           |      0 |    26123 | object         |
| Conclusion                               | Conclusion                               |      0 |    36480 | object         |
| D1_stenosis                              | D1_stenosis                              |      0 |        8 | float64        |
| D2_stenosis                              | D2_stenosis                              |      0 |        8 | float64        |
| D3_stenosis                              | D3_stenosis                              |      0 |        8 | float64        |
| RVG1_stenosis                            | RVG1_stenosis                            |      0 |        8 | float64        |
| RVG2_stenosis                            | RVG2_stenosis                            |      0 |        8 | float64        |
| S1_stenosis                              | S1_stenosis                              |      0 |        8 | float64        |
| bx_stenosis                              | bx_stenosis                              |      0 |        8 | float64        |
| dist_lad_stenosis                        | dist_lad_stenosis                        |      0 |        8 | float64        |
| dist_lcx_stenosis                        | dist_lcx_stenosis                        |      0 |        8 | float64        |
| dist_rca_stenosis                        | dist_rca_stenosis                        |      0 |        8 | float64        |

,CathReport_MRN,EXAMEN_ID,Num Accession,DICOMPath,ModalitiesInStudy,Patient_ID,QueryRetrieveLevel,StudyDate,StudyInstanceUID,StudyTime,year,patient_id_anon,dicom_id_x,study_time,series_time,IDPATIENT,DATEEXAMEN,TYPEEXAMEN,CATEGORIE,SOUSCATEGORIE,TITREEXAMEN,HEUREDEBUT,HEUREFIN,SALLE,NSEJOUR,FACTIVE,TYPEPROVENANCE,POIDS,TAILLE,HOSPITAL,Urgency,CREATININE,CK,HEMOGLOBINE,PLAQUETTES,TNI,TROPHS,ANGINA,ISCHEMIA,LOCALISATIONISCHEMIE,LV,DIABETES_HISTORY,HYPERTENSION,SMOKING,CAD_HISTORY,OTHERSURGERY,STROKE,VASCULAR,FIBRILLATION,TV,PM,CABG,LV.1,LVEF,RENAL,VASCULARACCESS,VASCULARACCESS2,FERMETUREART,FERMETUREART2,VEINACCESS,VEINACCESS2,FERMETUREVEIN,FERMETUREVEIN2,METHERGIN,LAO,RAO,STENTS,BMS,BALLONS,TRONC0,TRONC50,IVA50,CX50,CD50,PONTAGES,TC50,LESIONRESTENOSE,STENTSACTIFRESTENOSE,STENTSRESTENOSE,PONTAGESMAMMAIRES50,PONTAGESSAPHENES50,DILATATIONS,DILATATIONSPONTAGESSUCCES,TCDILATATIONS,PONTAGESSAPHENES,LESIONSSTENTSACTIF,DILATATIONSPONTAGESECHEC,DILATATIONSSUCCES,DILATATIONSECHEC,LESIONSSTENTS,STENTSACTIFS,PONTAGESMAMMAIRES,PONTAGES50,BVS,CDBMS,CDBVS,CDDEB,CDDILATATIONS,CDSTENTS,CDSTENTSACTIF,CIRCRESTENOSE,CXBMS,CXBVS,CXDEB,CXDILATATIONS,CXSTENTS,CXSTENTSACTIF,DEB,DILATATIONSPONTAGES,DSTENTMAX,DSTENTMIN,DSTENTMOY,GRAFTRESTENOSE,GUIDEPRESSION,IVABMS,IVABVS,IVADEB,IVADILATATIONS,IVASTENTS,IVASTENTSACTIF,IVUS,LADRESTENOSE,LESIONS50,LESIONSDILATATIONS,LMRESTENOSE,...,StationName,ProcedureCodeSequence,ManufacturerModelName,StartTrim,StopTrim,RecommendedDisplayFrameRate,PatientAge,PatientSize,PatientWeight,FPS,KVP,DeviceSerialNumber,SoftwareVersions,ProtocolName,FrameTime,DistanceSourceToDetector,DistanceSourceToPatient,EstimatedRadiographicMagnificationFactor,ExposureTime,XRayTubeCurrent,AveragePulseWidth,RadiationSetting,RadiationMode,ImageAndFluoroscopyAreaDoseProduct,IntensifierSize,ImagerPixelSpacing,FocalSpots,PositionerMotion,primary_angle,secondary_angle,PatientPosition,DetectorDescription,DetectorID,AcquisitionNumber,PatientOrientation,ImagesInAcquisition,NumberOfFrames,FrameIncrementPointer,PixelIntensityRelationship,WindowCenter,WindowWidth,VOILUTFunction,LossyImageCompression,RepresentativeFrameNumber,StudyIDIssuer,PerformedProcedureStepStartDate,PerformedProcedureStepStartTime,PerformedProcedureStepID,PerformedProcedureStepDescription,RequestAttributesSequence,PerformingPhysicianName,ReferencedSOPClassUID,ReferencedSOPInstanceUID,InstanceCreationDate,InstanceCreationTime,InstitutionalDepartmentName,ReferencedPerformedProcedureStepSequence,IrradiationEventUID,TableMotion,TableAngle,RequestedProcedureDescription,ScheduledProcedureStepDescription,ScheduledProcedureStepID,AcquisitionDateTime,FrameDelay,LossyImageCompressionMethod,ShutterShape,ShutterLeftVerticalEdge,ShutterRightVerticalEdge,ShutterUpperHorizontalEdge,ShutterLowerHorizontalEdge,DistanceSourceToEntrance,TableHorizontalRotationAngle,TableHeadTiltAngle,TableCradleTiltAngle,TableTopVerticalPosition,TableTopLongitudinalPosition,TableTopLateralPosition,OperatorsName,ReferencedStudySequence,ReferencedPatientSequence,XRayTubeCurrentInuA,AcquiredImageAreaDoseProduct,RequestedProcedureCodeSequence,ScheduledProtocolCodeSequence,ReferencedSeriesSequence,ShutterPresentationValue,SoftcopyVOILUTSequence,DisplayedAreaTopLeftHandCorner,DisplayedAreaBottomRightHandCorner,PresentationSizeMode,PresentationPixelAspectRatio,GraphicLayerSequence,GraphicLayer,GraphicLayerOrder,ContentLabel,PresentationCreationDate,PresentationCreationTime,PresentationLUTShape,PatientBirthTime,CollimatorShape,CollimatorLeftVerticalEdge,CollimatorRightVerticalEdge,CollimatorUpperHorizontalEdge,CollimatorLowerHorizontalEdge,fps,frame_time,series_description,dicom_id_y,FileName,Unnamed: 0,pred_contrast_agent,contrast_agent_class,pred_main_structure,main_structure_class,pred_stent_presence,stent_presence_class,pred_dominance,dominance_class,dicom_id,indication_first,indication_simplified,indication_acs_present,ACS_TYPE,Split
0,642272,150044,HE202400244201,/media/data1/ravram/DeepCORO/2024/642272/2.16.124.113611.1.118.1.1.6763805/1.2.392.200036.9116.1041.20240402124008750.2.5/1.2.392.200036.9116.1644.20240402135707312.3.52.dcm,nan,642272,nan,2024-04-02 08:22:00,2.16.124.113611.1.118.1.1.6763805,82142.0,2024.0,nan,1.2.392.200036.9116.1644.20240402135707312.3.52.dcm,-1,-1,568635.0,2024-04-02,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,08:22:00,09:49:00,4 - PRD,HE202400244201,1.0,Hôpital - Autre,50.6,155.0,Hospitalisé,Programmé,NaN,NaN,NaN,NaN,NaN,NaN,SCA (ST non sus-décalé),Ischémie documentée,nan,nan,Diabète (traitement per os),HTA,Non Fumeur,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,FEVG très diminuée (<30%),NaN,Insuf. rénale modérée,Artère fémorale droite,Aucun accès secondaire artériel,Perclose,Aucune fermeture artérielle secondaire,Veine fémorale droite,Aucun accès secondaire veineux,Perclose,Aucune fermeture venineuse principale,nan,nan,nan,2.0,0.0,1.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3.0,-1.0,1.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,...,24027004,nan,DFP-8000D,NaN,NaN,7.0,089Y,NaN,NaN,NaN,70.0,A1B2705X,V6.10*R007,Cardiac,133.333333,920.0,628.5259,1.463742,624.0,99.0,8.32,SC,nan,50.019,NaN,"[0.478834, 0.478834]",0.6,DYNAMIC,-3.0,0.0,HFS,nan,nan,NaN,nan,NaN,75.0,1577061.0,DISP,127.5,255.0,nan,NaN,38.0,nan,NaN,NaN,nan,nan,"[{'ScheduledProcedureStepDescription': 'CORONAROGRAPHIE', 'ScheduledProcedureStepID': 'HE202400244201', 'RequestedProcedureID': '2093546'}]",Nosair^Mohamed,1.2.840.10008.3.1.2.3.3,1.2.392.200036.9116.1041.20240402122142288.2.2,20240402.0,82142.126,Department,"[{'ReferencedSOPClassUID': '1.2.840.10008.3.1.2.3.3', 'ReferencedSOPInstanceUID': '1.2.392.200036.9116.1041.20240402122142288.2.2'}]",2.16.124.113611.1.118.1.1.6763805.0.8354760,STATIC,0.0,CORONAROGRAPHIE,CORONAROGRAPHIE,HE202400244201,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,1.2.392.200036.9116.1644.20240402135707312.3.52,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2024/1.2.392.200036.9116.1644.20240402135707312.3.52.mp4,925216.0,[0.006744],0.0,[8.6724312e-06 1.5106653e-03 1.0525566e-03 1.5826910e-05 9.9698693e-01\n 2.0916969e-08 2.5844437e-04 3.7221324e-07 9.4740390e-05 3.0025231e-07\n 2.9215354e-07 7.1234987e-05],4.0,[0.0005484],0.0,[1.],1.0,None,NSTEMI type 1,1. Acute Coronary Syndromes (ACS) - 1.2. NSTEMI (Non-ST-Elevation Myocardial Infarction),True,NSTEMI,TRAIN
1,642272,150044,HE202400244201,/media/data1/ravram/DeepCORO/2024/642272/2.16.124.113611.1.118.1.1.6763805/1.2.392.200036.9116.1041.20240402124118246.2.9/1.2.392.200036.9116.6662.20240402135719261.1.53.dcm,nan,642272,nan,2024-04-02 08:22:00,2.16.124.113611.1.118.1.1.6763805,82142.0,2024.0,nan,1.2.392.200036.9116.6662.20240402135719261.1.53.dcm,-1,-1,568635.0,2024-04-02,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,08:22:00,09:49:00,4 - PRD,HE202400244201,1.0,Hôpital - Autre,50.6,155.0,Hospitalisé,Programmé,NaN,NaN,NaN,NaN,NaN,NaN,SCA (ST non sus-décalé),Ischémie documentée,nan,nan,Diabète (traitement per os),HTA,Non Fumeur,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,FEVG très diminuée (<30%),NaN,Insuf. rénale modérée,Artère fémorale droite,Aucun accès secondaire artériel,Perclose,Aucune fermeture artérielle secondaire,Veine fémorale droite,Aucun accès secondaire veineux,Perclose,Aucune fermeture venineuse principale,nan,nan,nan,2.0,0.0,1.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3.0,-1.0,1.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,...,24027004,nan,DFP-8000D,NaN,NaN,7.0,089Y,NaN,NaN,NaN,70.0,A1B2705X,V6.10*R007,Cardiac,133.333333,920.0,628.5259,1.463742,262.0,102.0,8.47,SC,nan,0.654,NaN,"[0.478834, 0.478834]",0.6,DYNAMIC,-3.0,0.0,HFS,nan,nan,NaN,nan,NaN,31.0,1577061.0,DISP,127.5,255.0,nan,NaN,16.0,nan,NaN,NaN,nan,nan,"[{'ScheduledProcedureStepDescription': 'CORONAROGRAPHIE', 'ScheduledProcedureStepID': 'HE202400244201', 'RequestedProcedureID': '2093546'}]",Nosair^Mohamed,1.2.840.10008.3.1.2.3.3,1.2.392.200036.9116.1041.20240402122142288.2.2,20240402.0,82142.126,Department,"[{'ReferencedSOPClassUID': '1.2.840.10008.3.1.2.3.3', 'ReferencedSOPInstanceUID': '1.2.392.200036.9116.1041.20240402122142288.2.2'}]",2.16.124.113611.1.118.1.1.6763805.0.8411200,STATIC,0.0,CORONAROGRAPHIE,CORONAROGRAPHIE,HE202400244201,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,1.2.392.200036.9116.6662.20240402135719261.1.53,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2024/1.2.392.200036.9116.6662.20240402135719261.1.53.mp4,925217.0,[0.10034],0.0,[1.2008357e-03 1.5903741e-05 3.1876429e-05 6.3372357e-04 9.8822302e-01\n 1.7739255e-06 5.1943058e-05 2.2870217e-05 9.5379958e-03 2.2203281e-07\n 9.6838594e-06 2.7017604e-04],4.0,[0.0004356],0.0,[0.0806],0.0,None,NSTEMI type 1,1. Acute Coronary Syndromes (ACS) - 1.2. NSTEMI (Non-ST-Elevation Myocardial Infarction),True,NSTEMI,TRAIN
2,642272,150044,HE202400244201,/media/data1/ravram/DeepCORO/2024/642272/2.16.124.113611.1.118.1.1.6763805/1.2.392.200036.9116.1041.20240402124146702.2.13/1.2.392.200036.9116.6757.20240402135724535.1.54.dcm,nan,642272,nan,2024-04-02 08:22:00,2.16.124.113611.1.118.1.1.6763805,82142.0,2024.0,nan,1.2.392.200036.9116.6757.20240402135724535.1.54.dcm,-1,-1,568635.0,2024-04-02,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,08:22:00,09:49:00,4 - PRD,HE202400244201,1.0,Hôpital - Autre,50.6,155.0,Hospitalisé,Programmé,NaN,NaN,NaN,NaN,NaN,NaN,SCA (ST non sus-décalé),Ischémie documentée,nan,nan,Diabète (traitement per os),HTA,Non Fumeur,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,FEVG très diminuée (<30%),NaN,Insuf. rénale modérée,Artère fémorale droite,Aucun accès secondaire artériel,Perclose,Aucune fermeture artérielle secondaire,Veine fémorale droite,Aucun accès secondaire veineux,Perclose,Aucune fermeture venineuse principale,nan,nan,nan,2.0,0.0,1.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3.0,-1.0,1.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,...,24027004,nan,DFP-8000D,NaN,NaN,7.0,089Y,NaN,NaN,NaN,70.0,A1B2705X,V6.10*R007,Cardiac,133.333333,920.0,631.1427,1.457674,271.0,61.0,6.47,SC,nan,3.427,NaN,"[0.478834, 0.478834]",0.6,DYNAMIC,-3.0,0.0,HFS,nan,nan,NaN,nan,NaN,42.0,1577061.0,DISP,127.5,255.0,nan,NaN,21.0,nan,NaN,NaN,nan,nan,"[{'ScheduledProcedureStepDescription': 'CORONAROGRAPHIE', 'ScheduledProcedureStepID': 'HE202400244201', 'RequestedProcedureID': '2093546'}]",Nosair^Mohamed,1.2.840.10008.3.1.2.3.3,1.2.392.200036.9116.1041.20240402122142288.2.2,20240402.0,82142.126,Department,"[{'ReferencedSOPClassUID': '1.2.840.10008.3.1.2.3.3', 'ReferencedSOPInstanceUID': '1.2.392.200036.9116.1041.20240402122142288.2.2'}]",2.16.124.113611.1.118.1.1.6763805.0.8413890,STATIC,0.0,CORONAROGRAPHIE,CORONAROGRAPHIE,HE202400244201,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,1.2.392.200036.9116.6757.20240402135724535.1.54,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2024/1.2.392.200036.9116.6757.20240402135724535.1.54.mp4,925218.0,[0.694],1.0,[6.3587688e-03 1.9475652e-04 3.6716475e-03 7.1410227e-01 2.6065916e-01\n 2.6772501e-05 4.0656319e-03 2.8774559e-06 9.1397027e-03 1.6558615e-05\n 6.1893498e-04 1.1428513e-03],3.0,[0.01805],0.0,[0.519],1.0,None,NSTEMI type 1,1. Acute Coronary Syndromes (ACS) - 1.2. NSTEMI (Non-ST-Elevation Myocardial Infarction),True,NSTEMI,TRAIN
3,642272,150044,HE202400244201,/media/data1/ravram/DeepCORO/2024/642272/2.16.124.113611.1.118.1.1.6763805/1.2.392.200036.9116.1041.20240402124224526.2.17/1.2.392.200036.9116.3037.20240402135731495.3.55.dcm,nan,642272,nan,2024-04-02 08:22:00,2.16.124.113611.1.118.1.1.6763805,82142.0,2024.0,nan,1.2.392.200036.9116.3037.20240402135731495.3.55.dcm,-1,-1,568635.0,2024-04-02,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,08:22:00,09:49:00,4 - PRD,HE202400244201,1.0,Hôpital - Autre,50.6,155.0,Hospitalisé,Programmé,NaN,NaN,NaN,NaN,NaN,NaN,SCA (ST non sus-décalé),Ischémie documentée,nan,nan,Diabète (traitement per os),HTA,Non Fumeur,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,FEVG très diminuée (<30%),NaN,Insuf. rénale modérée,Artère fémorale droite,Aucun accès secondaire artériel,Perclose,Aucune fermeture artérielle secondaire,Veine fémorale droite,Aucun accès secondaire veineux,Perclose,Aucune fermeture venineuse principale,nan,nan,nan,2.0,0.0,1.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3.0,-1.0,1.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,...,24027004,nan,DFP-8000D,NaN,NaN,7.0,089Y,NaN,NaN,NaN,70.0,A1B2705X,V6.10*R007,Cardiac,133.333333,920.0,629.5726,1.461309,695.0,122.0,9.27,SC,nan,2.693,NaN,"[0.478834, 0.478834]",0.6,DYNAMIC,-3.0,0.0,HFS,nan,nan,NaN,nan,NaN,75.0,1577061.0,DISP,127.5,255.0,nan,NaN,38.0,nan,NaN,NaN,nan,nan,"[{'ScheduledProcedureStepDescription': 'CORONAROGRAPHIE', 'ScheduledProcedureStepID': 'HE202400244201', 'RequestedProcedureID': '2093546'}]",Nosair^Mohamed,1.2.840.10008.3.1.2.3.3,1.2.392.200036.9116.1041.20240402122142288.2.2,20240402.0,82142.126,Department,"[{'ReferencedSOPClassUID': '1.2.840.10008.3.1.2.3.3', 'ReferencedSOPInstanceUID': '1.2.392.200036.9116.1041.20240402122142288.2.2'}]",2.16.124.113611.1.118.1.1.6763805.0.8415710,STATIC,0.0,CORONAROGRAPHIE,CORONAROGRAPHIE,HE202400244201,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,1.2.392.200036.9116.3037.20240402135731495.3.55,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2024/1.2.392.200036.9116.3037.20240402135731495.3.55.mp4,925219.0,[0.02077],0.0,[5.7847890e-05 7.7907271e-06 2.1981314e-04 6.0582976e-03 9.8943287e-01\n 2.8433195e-07 1.2342447e-04 2.3480050e-07 3.2554648e-03 6.5456945e-08\n 7.7907271e-06 8.3607255e-04],4.0,[5.39e-05],0.0,[0.4114],0.0,None,NSTEMI type 1,1. Acute Coronary Syndromes (ACS) - 1.2. NSTEMI (Non-ST-Elevation Myocardial Infarction),True,NSTEMI,TRAIN
4,642272,150044,HE202400244201,/media/data1/ravram/DeepCORO/2024/642272/2.16.124.113611.1.118.1.1.6763805/1.2.392.200036.9116.1041.20240402124240190.2.21/1.2.392.200036.9116.4859.20240402135742851.1.56.dcm,nan,642272,nan,2024-04-02 08:22:00,2.16.124.113611.1.118.1.1.6763805,82142.0,2024.0,nan,1.2.392.200036.9116.4859.20240402135742851.1.56.dcm,-1,-1,568635.0,2024-04-02,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,08:22:00,09:49:00,4 - PRD,HE202400244201,1.0,Hôpital - Autre,50.6,155.0,Hospitalisé,Programmé,NaN,NaN,NaN,NaN,NaN,NaN,SCA (ST non sus-décalé),Ischémie documentée,nan,nan,Diabète (traitement per os),HTA,Non Fumeur,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,FEVG très diminuée (<30%),NaN,Insuf. rénale modérée,Artère fémorale droite,Aucun accès secondaire artériel,Perclose,Aucune fermeture artérielle secondaire,Veine fémorale droite,Aucun accès secondaire veineux,Perclose,Aucune fermeture venineuse principale,nan,nan,nan,2.0,0.0,1.0,3.0,3.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,1.0,0.0,2.0,0.0,3.0,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,3.0,-1.0,1.0,0.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0,0.0,...,24027004,nan,DFP-8000D,NaN,NaN,7.0,089Y,NaN,NaN,NaN,70.0,A1B2705X,V6.10*R007,Cardiac,133.333333,920.0,629.5726,1.461309,645.0,127.0,9.49,SC,nan,2.041,NaN,"[0.478834, 0.478834]",0.6,DYNAMIC,-3.0,0.0,HFS,nan,nan,NaN,nan,NaN,68.0,1577061.0,DISP,127.5,255.0,nan,NaN,34.0,nan,NaN,NaN,nan,nan,"[{'ScheduledProcedureStepDescription': 'CORONAROGRAPHIE', 'ScheduledProcedureStepID': 'HE202400244201', 'RequestedProcedureID': '2093546'}]",Nosair^Mohamed,1.2.840.10008.3.1.2.3.3,1.2.392.200036.9116.1041.20240402122142288.2.2,20240402.0,82142.126,Department,"[{'ReferencedSOPClassUID': '1.2.840.10008.3.1.2.3.3', 'ReferencedSOPInstanceUID': '1.2.392.200036.9116.1041.20240402122142288.2.2'}]",2.16.124.113611.1.118.1.1.6763805.0.8422760,STATIC,0.0,CORONAROGRAPHIE,CORONAROGRAPHIE,HE202400244201,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,1.2.392.200036.9116.4859.20240402135742851.1.56,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2024/1.2.392.200036.9116.4859.20240402135742851.1.56.mp4,925220.0,[0.02611],0.0,[5.3516660e-06 4.5039273e-05 4.2590305e-05 1.5322388e-04 9.9959272e-01\n 1.6205625e-08 5.0824801e-05 8.2770244e-09 9.2844268e-05 2.2723472e-07\n 3.1795852e-07 1.6776616e-05],4.0,[3.45e-05],0.0,[0.685],1.0,None,NSTEMI type 1,1. Acute Coronary Syndromes (ACS) - 1.2. NSTEMI (Non-ST-Elevation Myocardial Infarction),True,NSTEMI,TRAIN

In [9]:
row = df[df['FileName'].str.contains("2.16.124.113611.1.118.1.1.5708095_1.2.276.0.7230010.3.1.3.477015473.4564.1613021426.619.dcm.avi", na=False)]
display(row)

,CathReport_MRN,EXAMEN_ID,Num Accession,DICOMPath,ModalitiesInStudy,Patient_ID,QueryRetrieveLevel,StudyDate,StudyInstanceUID,StudyTime,year,patient_id_anon,dicom_id_x,study_time,series_time,IDPATIENT,DATEEXAMEN,TYPEEXAMEN,CATEGORIE,SOUSCATEGORIE,TITREEXAMEN,HEUREDEBUT,HEUREFIN,SALLE,NSEJOUR,FACTIVE,TYPEPROVENANCE,POIDS,TAILLE,HOSPITAL,Urgency,CREATININE,CK,HEMOGLOBINE,PLAQUETTES,TNI,TROPHS,ANGINA,ISCHEMIA,LOCALISATIONISCHEMIE,LV,DIABETES_HISTORY,HYPERTENSION,SMOKING,CAD_HISTORY,OTHERSURGERY,STROKE,VASCULAR,FIBRILLATION,TV,PM,CABG,LV.1,LVEF,RENAL,VASCULARACCESS,VASCULARACCESS2,FERMETUREART,FERMETUREART2,VEINACCESS,VEINACCESS2,FERMETUREVEIN,FERMETUREVEIN2,METHERGIN,LAO,RAO,STENTS,BMS,BALLONS,TRONC0,TRONC50,IVA50,CX50,CD50,PONTAGES,TC50,LESIONRESTENOSE,STENTSACTIFRESTENOSE,STENTSRESTENOSE,PONTAGESMAMMAIRES50,PONTAGESSAPHENES50,DILATATIONS,DILATATIONSPONTAGESSUCCES,TCDILATATIONS,PONTAGESSAPHENES,LESIONSSTENTSACTIF,DILATATIONSPONTAGESECHEC,DILATATIONSSUCCES,DILATATIONSECHEC,LESIONSSTENTS,STENTSACTIFS,PONTAGESMAMMAIRES,PONTAGES50,BVS,CDBMS,CDBVS,CDDEB,CDDILATATIONS,CDSTENTS,CDSTENTSACTIF,CIRCRESTENOSE,CXBMS,CXBVS,CXDEB,CXDILATATIONS,CXSTENTS,CXSTENTSACTIF,DEB,DILATATIONSPONTAGES,DSTENTMAX,DSTENTMIN,DSTENTMOY,GRAFTRESTENOSE,GUIDEPRESSION,IVABMS,IVABVS,IVADEB,IVADILATATIONS,IVASTENTS,IVASTENTSACTIF,IVUS,LADRESTENOSE,LESIONS50,LESIONSDILATATIONS,LMRESTENOSE,...,StationName,ProcedureCodeSequence,ManufacturerModelName,StartTrim,StopTrim,RecommendedDisplayFrameRate,PatientAge,PatientSize,PatientWeight,FPS,KVP,DeviceSerialNumber,SoftwareVersions,ProtocolName,FrameTime,DistanceSourceToDetector,DistanceSourceToPatient,EstimatedRadiographicMagnificationFactor,ExposureTime,XRayTubeCurrent,AveragePulseWidth,RadiationSetting,RadiationMode,ImageAndFluoroscopyAreaDoseProduct,IntensifierSize,ImagerPixelSpacing,FocalSpots,PositionerMotion,primary_angle,secondary_angle,PatientPosition,DetectorDescription,DetectorID,AcquisitionNumber,PatientOrientation,ImagesInAcquisition,NumberOfFrames,FrameIncrementPointer,PixelIntensityRelationship,WindowCenter,WindowWidth,VOILUTFunction,LossyImageCompression,RepresentativeFrameNumber,StudyIDIssuer,PerformedProcedureStepStartDate,PerformedProcedureStepStartTime,PerformedProcedureStepID,PerformedProcedureStepDescription,RequestAttributesSequence,PerformingPhysicianName,ReferencedSOPClassUID,ReferencedSOPInstanceUID,InstanceCreationDate,InstanceCreationTime,InstitutionalDepartmentName,ReferencedPerformedProcedureStepSequence,IrradiationEventUID,TableMotion,TableAngle,RequestedProcedureDescription,ScheduledProcedureStepDescription,ScheduledProcedureStepID,AcquisitionDateTime,FrameDelay,LossyImageCompressionMethod,ShutterShape,ShutterLeftVerticalEdge,ShutterRightVerticalEdge,ShutterUpperHorizontalEdge,ShutterLowerHorizontalEdge,DistanceSourceToEntrance,TableHorizontalRotationAngle,TableHeadTiltAngle,TableCradleTiltAngle,TableTopVerticalPosition,TableTopLongitudinalPosition,TableTopLateralPosition,OperatorsName,ReferencedStudySequence,ReferencedPatientSequence,XRayTubeCurrentInuA,AcquiredImageAreaDoseProduct,RequestedProcedureCodeSequence,ScheduledProtocolCodeSequence,ReferencedSeriesSequence,ShutterPresentationValue,SoftcopyVOILUTSequence,DisplayedAreaTopLeftHandCorner,DisplayedAreaBottomRightHandCorner,PresentationSizeMode,PresentationPixelAspectRatio,GraphicLayerSequence,GraphicLayer,GraphicLayerOrder,ContentLabel,PresentationCreationDate,PresentationCreationTime,PresentationLUTShape,PatientBirthTime,CollimatorShape,CollimatorLeftVerticalEdge,CollimatorRightVerticalEdge,CollimatorUpperHorizontalEdge,CollimatorLowerHorizontalEdge,fps,frame_time,series_description,dicom_id_y,FileName,Unnamed: 0,pred_contrast_agent,contrast_agent_class,pred_main_structure,main_structure_class,pred_stent_presence,stent_presence_class,pred_dominance,dominance_class,dicom_id,indication_first,indication_simplified,indication_acs_present,ACS_TYPE,Split
208209,586102,83758,HE202100111501,/media/data1/ravram/DeepCORO/2021/283247173028279189934458512077088961358/2.16.124.113611.1.118.1.1.5708095/1.2.276.0.7230010.3.1.3.477015473.4564.1613021426.619.dcm,XA,586102,STUDY,2021-02-10 23:06:00,2.16.124.113611.1.118.1.1.5708095,225711.0,2021.0,283247173028279189934458512077088961358,None,225711,3019,465632.0,2021-02-10,Coro+Angio,1.0,1.0,Coronarographie et Angioplastie,23:06:00,23:44:00,4 - PRD,HE202100111501,1.0,Hôpital SAU,121.0,180.0,Hospitalisé,Urgent,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,nan,Diabète (traitement per os),HTA,Tabagisme Actuel,Absence d'hérédité,Pas d'autre chirurgie cardiaque,Pas d'ATCD AVC,Pas de pathologie vasculaire périphérique,Pas de FA,Pas de TV,Pas de PM,Pas d'ATCD de pontages,nan,NaN,Pas d'insuf. rénale,Artère radiale droite,Aucun accès secondaire artériel,BENGAL,Aucune fermeture artérielle secondaire,Aucun accès principal veineux,Aucun accès secondaire veineux,Aucune fermeture veineuse principale,Aucune fermeture venineuse principale,nan,nan,nan,1.0,0.0,0.0,3.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,nan,nan,nan,NaN,NaN,NaN,nan,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,nan,nan,nan,NaN,nan,NaN,NaN,NaN,nan,nan,nan,nan,NaN,NaN,nan,NaN,NaN,nan,nan,nan,nan,nan,nan,NaN,NaN,nan,nan,nan,nan,NaN,nan,nan,nan,NaN,NaN,nan,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nan,nan,nan,NaN,NaN,nan,nan,nan,NaN,nan,nan,nan,nan,nan,nan,nan,NaN,nan,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,nan,None,/media/data1/ravram/MHI_CATH_DICOM_VIDEOS/2021/2.16.124.113611.1.118.1.1.5708095_1.2.276.0.7230010.3.1.3.477015473.4564.1613021426.619.dcm.avi,137491.0,[1.43e-06],0.0,[4.7126669e-05 2.4840748e-04 9.9146664e-01 4.8567917e-06 5.0822184e-03\n 2.8901105e-03 2.3812769e-05 5.0757419e-05 1.3752829e-06 3.2739463e-05\n 1.4021418e-04 1.1788175e-05],2.0,[0.013954],0.0,[0.999],1.0,1.2.276.0.7230010.3.1.3.477015473.4564.1613021426.619.dcm,nan,Other,False,NON_ACS,TRAIN

# Train Below

In [ ]:
import os
import sys

## CHANGE THIS
dir2 = os.path.abspath("/volume/Orion/orion")
dir1 = os.path.dirname(dir2)
if not dir1 in sys.path:
    sys.path.append(dir1)
import importlib

importlib.util.find_spec("orion")

import csv

import numpy as np
import pandas as pd
from IPython.core.display import HTML, display

display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option("display.max_rows", 50)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 300)
pd.options.mode.chained_assignment = None  # default='warn'

In [ ]:
import torch

print(torch.cuda.device_count())
print(torch.version.cuda)
print(torch._C._cuda_getCompiledVersion(), "cuda compiled version")

import torchvision

#torch.set_num_threads(num_threads)

print(torchvision.__version__, "Torchvision version")
print("Torch version", torch.__version__)
print(torch.cuda.get_arch_list())

print(torch.cuda.nccl.version())
print("Are GPUS available", torch.cuda.is_available())

In [ ]:
import pandas as pd
## Load  /volume/Orion/data/DeepCORO_ALGO1_ObjectRecong_with_CathEF_UCSF_MHI_dataset_train_test_dev_NAS_path_mu.csv
df = pd.read_csv('/volume/Orion/data/DeepCORO_ALGO1_ObjectRecong_with_CathEF_UCSF_MHI_dataset_train_test_dev_NAS_path_small_mu.csv', sep='µ')
display(df.Split.value_counts())
display(df.object_pred.value_counts())
display(df.head(n=5))
#display(df.loc[df['Split']=='TEST'])
#df["Value"] = df['Value']*100
#df.to_csv('/volume/Orion/data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_NAS_path_mu.csv', sep='µ')
#display(df.Value.value_counts())

### Sweep

In [ ]:
import wandb
import yaml

def load_yaml_config(file_path):
    with open(file_path, 'r') as file:
        return yaml.safe_load(file)

sweep_conf_file_path = 'config/sweep_config.yaml'
sweep_conf = load_yaml_config(sweep_conf_file_path)
count = 1  # number of runs to execute

#sweep_id = wandb.sweep(sweep_conf,project=sweep_conf['name'])
sweep_id = 'mvjk19ll'
wandb.agent(
    sweep_id=sweep_id,
    entity="mhi_ai",
    project=sweep_conf['name'])

#wandb.agent("aiehwvid", project="retry-deadlock", function=train)

### Regression

In [ ]:
import os
import os
df = pd.read_csv(
    "../data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_NAS_path_small_mu.csv",
    sep="µ",
)
df.loc[df['Split']=='TEST'].y_true_cat.head(n=10)
#df['y_true_cat'] = np.where(df['Value'] < 40.00, 1, 0)
#df['FileName'] = df['FileName'].str.replace('/volume/Orion/exported_videos_512_by_512_MHI_UCSF/', '/media/data1/ravram/exported_videos_512_by_512_MHI_UCSF/')
#df = df.sample(100)
#df.to_csv('/volume/Orion/data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_new_small_mu.csv', sep="µ")
#for file_name in df['FileName']:
#    if os.path.exists(file_name):
#        continue
#    else:
#        print(f"{file_name} does not exist")
#df = df.sample(200)
#df.to_csv('../data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_NAS_path_small_mu.csv', sep="µ")

#file_name = "/volume/Orion/exported_videos_512_by_512_MHI_UCSF/66661628_2469453.dcm.avi"
#split = df.loc[df['FileName'] == file_name, 'Split'].values[0]
#print(split)

In [ ]:
##Load /volume/Orion/data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_15_FPS_only_exclude_outliers_mu.csv with mu separator
#df = pd.read_csv(
#    "/volume/Orion/data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_15_FPS_only_exclude_outliers_mu.csv",
#    sep="µ",
#)
#display(df.Value.describe())
#display(df.FileName)

def min_max_scaling(value, min_val=10, max_val=74.9):
    """
    Apply min-max scaling to a given value.

    Parameters:
    value (float): The value to be scaled.
    min_val (float): The minimum value of the original range.
    max_val (float): The maximum value of the original range.

    Returns:
    float: The scaled value.
    """
    return (value - min_val) / (max_val - min_val)

# Example usage
#df['Value_min_max'] = min_max_scaling(df['Value'])
#display(df['Value_min_max'].describe())

#df.to_csv(
#    "/volume/Orion/data/train_val_test_LCA_REGRESSION_with_MHI_2021_data_15_FPS_only_exclude_outliers_min_maxmu.csv",
#    sep="µ",
#)

In [ ]:
# from orion.utils import video_regress_ddp
from orion.utils import video_training_and_eval
import wandb
import yaml
os.environ["WANDB_NOTEBOOK_NAME"] = "test_view_classifier.ipynb"
# Set environment variables for 'env://' initialization
os.environ['RANK'] = '0'
os.environ['WORLD_SIZE'] = '1'
os.environ['MASTER_ADDR'] = 'localhost'
os.environ['MASTER_PORT'] = '12355'  # Use an open port


class Args:
    def __init__(self):
        self.local_rank = 0  # Set default values as needed
        self.log_all = False
        self.epochs = 2
        self.batch = 32


# Create an instance of Args
args = Args()

# Load configuration from YAML file
with open('config/config_small.yaml', 'r') as file:
    config_defaults = yaml.safe_load(file)
# Create the transforms
transform_list = video_training_and_eval.create_transforms(config_defaults)

# Initialize a wandb run if logging, otherwise return None
run = video_training_and_eval.setup_run(args, config_defaults)
# Run the main process
video_training_and_eval.execute_run(config_defaults=config_defaults, transforms=transform_list, args=args, run=run)

# Plot predictions for sanity check

In [ ]:
### import os
import os
import sys

## CHANGE THIS
dir2 = os.path.abspath("/volume/Orion/orion")
dir1 = os.path.dirname(dir2)
if not dir1 in sys.path:
    sys.path.append(dir1)
import importlib

importlib.util.find_spec("orion")
import csv

import numpy as np
import pandas as pd
from IPython.core.display import HTML, display

display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option("display.max_rows", 50)
pd.set_option("display.max_columns", 250)
pd.set_option("display.width", 1000)
pd.set_option("display.max_colwidth", 300)
pd.options.mode.chained_assignment = None  # default='warn'

In [ ]:
dir2 = os.path.abspath("/volume/DicomVideoProcessing/downloadAvi/")
dir1 = os.path.dirname(dir2)
if not dir1 in sys.path:
    sys.path.append(dir1)
import importlib

importlib.util.find_spec("downloadAvi")
from downloadAvi import plot_avi as plot_avi

In [ ]:

df_predictions = pd.read_csv('../trained_models/swin3d_s_2_24_1_RAdam_new_20231222-154107/test_predictions.csv')
df_predictions = df_predictions.rename(columns={'filename': 'FileName'})

class_mapping = {
    0: "Aorta",
    1: "Catheter",
    2: "Femoral",
    3: "Graft",
    4: "LV",
    5: "Left",
    6: "Other",
    7: "Pigtail",
    8: "Radial",
    9: "Right",
    10: "Stenting"
}

def get_predicted_class(prob_string):
    prob_array = np.array([float(num) for num in prob_string.strip("[]").split()])
    predicted_class = np.argmax(prob_array)
    return predicted_class, class_mapping[predicted_class]

# Apply the function to each row in the 'y_pred' column
df_predictions[['y_pred', 'predicted_class']] = df_predictions['y_hat'].apply(get_predicted_class).apply(pd.Series)

df_predictions['y_true_mapped'] = df_predictions['y_true'].map(class_mapping)

#print(df_predictions.head(n=25))
# Example usage
# Assuming your DataFrame is named df
plot_avi.sample_and_plot_middle_frames(df_predictions, N=15, label_column='y_true_mapped', second_label_column='predicted_class')

In [ ]:
mismatched_instances = df_predictions[df_predictions['y_true'] != df_predictions['y_pred']]
print(len(mismatched_instances))
# Assuming your DataFrame is named df
plot_avi.sample_and_plot_middle_frames(mismatched_instances, N=25, label_column='y_true_mapped', second_label_column='predicted_class')

In [ ]:
import pandas as pd
## Load  /volume/Orion/data/DeepCORO_ALGO1_ObjectRecong_with_CathEF_UCSF_MHI_dataset_train_test_dev_NAS_path_mu.csv
df = pd.read_csv('/volume/Orion/data/DeepCORO_ALGO1_ObjectRecong_with_CathEF_UCSF_MHI_dataset_train_test_dev_NAS_path_mu.csv', sep='µ')
display(df.head(n=5))

In [ ]:
## Find how manydf['FileName'] is in df_predictions['FileName']
display(df.loc[df['FileName'].isin(df_predictions['FileName'])].Split.value_counts())
display(df['FileName'].isin(df_predictions['FileName']).value_counts())